#!/usr/bin/env python3


from argparse import ArgumentParser
from mechanicalsoup import StatefulBrowser
from getpass import getpass
import http.client
import logging
import sys




logging.getLogger("urllib3").setLevel(logging.DEBUG)

logging.getLogger().setLevel(logging.DEBUG)
request_logger = logging.getLogger('requests.packages.urllib3')
request_logger.setLevel(logging.DEBUG)
request_logger.propagate = True

http.client.HTTPConnection.debuglevel = 1




parser = ArgumentParser(description='Redmine Time Tracking Tool '
    'for adding time tracking entries from CSV data')
parser.add_argument('url', metavar='URL',
    help='Base URL of Redmine installation')
parser.add_argument('--user', '-u', required=True,
    help='Redmine user name')


args = parser.parse_args()
password = getpass(stream=sys.stderr)




browser = StatefulBrowser()
browser.set_verbose(2)

browser.open(args.url + '/login')
form = browser.select_form('#login-form form')
form['username'] = args.user
form['password'] = password
# browser.get_current_form().print_summary()
response = browser.submit_selected()

browser.open(args.url + '/issues/858/time_entries/new')
print('current url: {}'.format(browser.get_url()))

# I did not succeed in looking up the form via its ID '#new_time_entry'.
form = browser.select_form('form[class=new_time_entry]')
form.print_summary()
# Beware: Despite my test installation with German date format is showing
# 02.11.2019 in the browser, the actual date is sent in ISO 8601 (YYYY-MM-DD)
# over the wire.
form['time_entry[spent_on]'] = '2019-11-02'
form['time_entry[hours]'] = '1.42'
form['time_entry[comments]'] = 'A late entry'
form['time_entry[activity_id]'] = '9'
form.choose_submit('continue')
response = browser.submit_selected()
